In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2
%load_ext memory_profiler
%load_ext line_profiler

### numpy索引速度测试

In [1]:
import numpy as np

In [31]:
ppos1 = np.random.random([10000000, 3])
pid = np.random.random([10000000, 1]) * 10000000
pid2 = pid.astype("int")

In [32]:
%%timeit
for i in range(100):
    np.take(ppos1, pid2.astype("int")[:, 0]-1, axis=0)

40.9 s ± 38.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [33]:
%%timeit
for i in range(100):
    ppos1[pid2[:, 0] - 1]

1min 11s ± 66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [2]:
import displacement
import numpy as np

In [3]:
100*np.ones([3,1], dtype=np.int32)

array([[100],
       [100],
       [100]], dtype=int32)

In [6]:
displacement.WriteDTFE(filename="write_test", Npart=5, BoxSize=600., pos=np.ones([5,3], dtype=np.float32), vel=np.zeros([5,3], dtype=np.float32), weight=3, DustType="Uniform", Ndust=3, WeightDust=100*np.ones([3,1], dtype=np.float32))

In [7]:
displacement.ReadDTFE(filename="write_test")

{'BoxSize': array([  0., 600.,   0., 600.,   0., 600.], dtype=float32),
 'pos': array([[  1.       ,   1.       ,   1.       ],
        [  1.       ,   1.       ,   1.       ],
        [  1.       ,   1.       ,   1.       ],
        [  1.       ,   1.       ,   1.       ],
        [  1.       ,   1.       ,   1.       ],
        [112.278    , 480.41116  , 479.62973  ],
        [390.0172   ,   7.0512652, 520.96857  ],
        [444.69693  , 569.88873  ,  68.39071  ]], dtype=float32),
 'weight': array([[1077936128],
        [1077936128],
        [1077936128],
        [1077936128],
        [1077936128],
        [1120403456],
        [1120403456],
        [1120403456]], dtype=int32),
 'vel': array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32)}

In [8]:
np.ones([0, 3])

array([], shape=(0, 3), dtype=float64)

In [9]:
np.vstack((np.ones([3, 3]), np.ones([0, 3])))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.vstack((np.ones([5,3], dtype=np.float32), np.ones([5,3], dtype=np.float32)))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)